name: budgetopia
description: A money manager application for personal use.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  another_flushbar: ^1.12.32                        #Notificações na parte inferior
  adaptive_theme: ^3.7.2                            #Alterar o tema do aplicativo
  animations: ^2.1.1                                #Efeitos de animações prontos
  animated_list_plus: ^0.5.2
  fl_chart: ^1.1.1                                  #Gráficos
  flex_color_scheme:  ^8.4.0                        #Controla o tema do aplicativo
  flutter_native_splash: ^2.4.7
  flutter_zoom_drawer: ^3.2.0                       #Drawer
  font_awesome_flutter: ^10.12.0                    #Mais ícones
  intl: ^0.20.2
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  lottie: ^3.3.2                                    #Animações
  objectbox: ^5.2.0                                 #Armazenamento de dados
  objectbox_flutter_libs: ^5.2.0                    #Armazenamento de dados
  path_provider: ^2.1.5
  path: ^1.9.1
  permission_handler: ^12.0.1
  rflutter_alert: ^2.0.7
  flutter_ddi: ^0.11.1

  meta: any
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  build_runner: ^2.11.1

  #flutter_launcher_icons: "^0.13.1"
  objectbox_generator: ^5.2.0

objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/custom (and test/custom).
  output_dir: "config/banco/generated"


flutter_native_splash:
  background_image: "assets/app/splash.png"
  color: "#b5f2b0"
  color_dark: "#003822"
  android: true
  android_gravity: fill_vertical

  android_12:
    background_image: "assets/app/splash.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/app/
    - assets/icons/