name: budgetopia
description: A money manager application for personal use.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  another_flushbar: ^1.12.30                        #Notificações na parte inferior
  adaptive_theme: ^3.6.0                            #Alterar o tema do aplicativo
  animations: ^2.0.11                               #Efeitos de animações prontos
  animated_list_plus: ^0.5.2
  fl_chart: ^0.69.0                                 #Gráficos
  flex_color_scheme:  ^7.3.1                        #Controla o tema do aplicativo
  flutter_native_splash: ^2.3.10
  flutter_zoom_drawer: ^3.2.0                       #Drawer
  font_awesome_flutter: ^10.7.0                     #Mais ícones
  intl: ^0.19.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  lottie: ^3.1.3                                    #Animações
  objectbox: ^4.0.3                                 #Armazenamento de dados
  objectbox_flutter_libs: ^4.0.3                    #Armazenamento de dados
  path_provider: ^2.1.4
  path: ^1.9.0
  permission_handler: ^11.3.1
  flutter_ddi: ^0.5.1
  rflutter_alert: ^2.0.7
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.4.13

  #flutter_launcher_icons: "^0.13.1"
  objectbox_generator: ^4.0.3

objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/custom (and test/custom).
  output_dir: "config/banco/generated"


flutter_native_splash:
  background_image: "assets/app/splash.png"
  color: "#b5f2b0"
  color_dark: "#003822"
  android: true
  android_gravity: fill_vertical

  android_12:
    background_image: "assets/app/splash.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/app/
    - assets/icons/