enum CategoriaEnum {
  Academia(34, 'Academia', 'esportes.png'),
  Acessorios(35, 'Acessorios', 'compras.png'),
  Advogado(71, 'Advogado', 'contas.png'),
  Agua(55, 'Agua', 'contas.png'),
  Alfandega(72, 'Alfandega', 'impostos.png'),
  Alimentacao(1, 'Alimentacao', 'alimentacao.png'),
  Aluguel(2, 'Aluguel', 'aluguel.png'),
  Animais(3, 'Animais', 'animais.png'),
  Aplicativos(73, 'Aplicativos', 'tecnologia.png'),
  Artesanato(74, 'Artesanato', 'hobbies.png'),
  Assinaturas(36, 'Assinaturas', 'tecnologia.png'),
  Banco(37, 'Banco', 'money.png'),
  Bares(75, 'Bares', 'bebidas.png'),
  Bebidas(4, 'Bebidas', 'bebidas.png'),
  Beleza(5, 'Beleza', 'beleza.png'),
  Bicicleta(76, 'Bicicleta', 'transporte.png'),
  Bonificacao(77, 'Bonificacao', 'money.png'),
  Cambio(79, 'Cambio', 'money.png'),
  Caridade(6, 'Caridade', 'caridade.png'),
  CartaoCredito(80, 'Cartao Credito', 'money.png'),
  Casa(38, 'Casa', 'manutencao.png'),
  Cashback(78, 'Cashback', 'money.png'),
  CinemaTeatro(81, 'Cinema e Teatro', 'entretenimento.png'),
  ClinicaVeterinaria(82, 'Clinica Veterinaria', 'animais.png'),
  Combustivel(39, 'Combustivel', 'transporte.png'),
  Compras(7, 'Compras', 'compras.png'),
  Comunicacao(40, 'Comunicacao', 'tecnologia.png'),
  Condominio(56, 'Condominio', 'aluguel.png'),
  Contas(8, 'Contas', 'contas.png'),
  Corretagem(83, 'Corretagem', 'investimentos.png'),
  Creche(57, 'Creche', 'filhos.png'),
  CuidadosPessoais(9, 'Cuidados Pessoais', 'cuidados_pessoais.png'),
  Cursos(41, 'Cursos', 'educacao.png'),
  Decoracao(84, 'Decoracao', 'compras.png'),
  Delivery(42, 'Delivery', 'alimentacao.png'),
  Dentista(58, 'Dentista', 'saude.png'),
  Dividendos(85, 'Dividendos', 'investimentos.png'),
  Educacao(10, 'Educacao', 'educacao.png'),
  Eletrodomesticos(86, 'Eletrodomesticos', 'eletronicos.png'),
  Eletronicos(11, 'Eletronicos', 'eletronicos.png'),
  Energia(12, 'Energia', 'energia.png'),
  Entretenimento(13, 'Entretenimento', 'entretenimento.png'),
  Esportes(14, 'Esportes', 'esportes.png'),
  Estacionamento(59, 'Estacionamento', 'transporte.png'),
  Eventos(15, 'Eventos', 'eventos.png'),
  Exames(87, 'Exames', 'saude.png'),
  Farmacia(43, 'Farmacia', 'saude.png'),
  Feira(88, 'Feira', 'alimentacao.png'),
  Ferramentas(89, 'Ferramentas', 'manutencao.png'),
  Festas(16, 'Festas', 'festas.png'),
  Filhos(17, 'Filhos', 'filhos.png'),
  Financiamento(90, 'Financiamento', 'money.png'),
  Fotografia(91, 'Fotografia', 'hobbies.png'),
  Franquias(92, 'Franquias', 'investimentos.png'),
  Freelance(60, 'Freelance', 'money.png'),
  GiftCards(61, 'Gift Cards', 'presentes.png'),
  Higiene(62, 'Higiene', 'cuidados_pessoais.png'),
  Hobbies(18, 'Hobbies', 'hobbies.png'),
  Hotel(44, 'Hotel', 'viagem.png'),
  Impostos(19, 'Impostos', 'impostos.png'),
  Imprevistos(20, 'Imprevistos', 'imprevistos.png'),
  Internet(45, 'Internet', 'tecnologia.png'),
  Investimentos(21, 'Investimentos', 'investimentos.png'),
  Jogos(22, 'Jogos', 'jogos.png'),
  Juros(93, 'Juros', 'money.png'),
  Lavanderia(63, 'Lavanderia', 'roupas.png'),
  Lazer(23, 'Lazer', 'lazer.png'),
  Licencas(64, 'Licencas', 'tecnologia.png'),
  Limpeza(94, 'Limpeza', 'manutencao.png'),
  Livros(24, 'Livros', 'livros.png'),
  Manutencao(25, 'Manutencao', 'manutencao.png'),
  Marketing(95, 'Marketing', 'tecnologia.png'),
  MaterialEscolar(65, 'Material Escolar', 'livros.png'),
  Mensalidade(66, 'Mensalidade', 'educacao.png'),
  Mobiliario(96, 'Mobiliario', 'compras.png'),
  Moradia(46, 'Moradia', 'aluguel.png'),
  Musica(26, 'Musica', 'musica.png'),
  Outros(99, 'Outros', 'outros.png'),
  Padaria(47, 'Padaria', 'alimentacao.png'),
  Papelaria(48, 'Papelaria', 'livros.png'),
  Parcelas(67, 'Parcelas', 'contas.png'),
  Presentes(27, 'Presentes', 'presentes.png'),
  PrevidenciaPrivada(97, 'Previdencia Privada', 'seguros.png'),
  Reembolso(98, 'Reembolso', 'money.png'),
  RefeicoesTrabalho(68, 'Refeicoes Trabalho', 'alimentacao.png'),
  Reparos(69, 'Reparos', 'manutencao.png'),
  Restaurante(49, 'Restaurante', 'alimentacao.png'),
  Roupas(28, 'Roupas', 'roupas.png'),
  Salario(50, 'Salario', 'money.png'),
  Saude(29, 'Saude', 'saude.png'),
  Seguros(30, 'Seguros', 'seguros.png'),
  Servicos(51, 'Servicos', 'contas.png'),
  Streaming(70, 'Streaming', 'entretenimento.png'),
  Supermercado(52, 'Supermercado', 'alimentacao.png'),
  Taxas(54, 'Taxas', 'impostos.png'),
  Tecnologia(31, 'Tecnologia', 'tecnologia.png'),
  Telefone(53, 'Telefone', 'tecnologia.png'),
  Transporte(32, 'Transporte', 'transporte.png'),
  VendaDeItens(100, 'Venda de Itens', 'money.png'),
  Viagem(33, 'Viagem', 'viagem.png');

  const CategoriaEnum(this.id, this.nome, this.icone);
  final String nome;
  final int id;
  final String icone;

  static final Map<int, CategoriaEnum> _findById = Map.fromEntries(
    CategoriaEnum.values.map((value) => MapEntry(value.id, value)),
  );

  static CategoriaEnum? getById(int value) => _findById[value];
}
