import 'package:budgetopia/common/constantes/strings.dart';

enum CategoriaEnum {
  Academia(34, 'esportes.png'),
  Acessorios(35, 'compras.png'),
  Advogado(71, 'contas.png'),
  Agua(55, 'contas.png'),
  Alfandega(72, 'impostos.png'),
  Alimentacao(1, 'alimentacao.png'),
  Aluguel(2, 'aluguel.png'),
  Animais(3, 'animais.png'),
  Aplicativos(73, 'tecnologia.png'),
  Artesanato(74, 'hobbies.png'),
  Assinaturas(36, 'tecnologia.png'),
  Banco(37, 'money.png'),
  Bares(75, 'bebidas.png'),
  Bebidas(4, 'bebidas.png'),
  Beleza(5, 'beleza.png'),
  Bicicleta(76, 'transporte.png'),
  Bonificacao(77, 'money.png'),
  Cambio(79, 'money.png'),
  Caridade(6, 'caridade.png'),
  CartaoCredito(80, 'money.png'),
  Casa(38, 'manutencao.png'),
  Cashback(78, 'money.png'),
  CinemaTeatro(81, 'entretenimento.png'),
  ClinicaVeterinaria(82, 'animais.png'),
  Combustivel(39, 'transporte.png'),
  Compras(7, 'compras.png'),
  Comunicacao(40, 'tecnologia.png'),
  Condominio(56, 'aluguel.png'),
  Contas(8, 'contas.png'),
  Corretagem(83, 'investimentos.png'),
  Creche(57, 'filhos.png'),
  CuidadosPessoais(9, 'cuidados_pessoais.png'),
  Cursos(41, 'educacao.png'),
  Decoracao(84, 'compras.png'),
  Delivery(42, 'alimentacao.png'),
  Dentista(58, 'saude.png'),
  Dividendos(85, 'investimentos.png'),
  Educacao(10, 'educacao.png'),
  Eletrodomesticos(86, 'eletronicos.png'),
  Eletronicos(11, 'eletronicos.png'),
  Energia(12, 'energia.png'),
  Entretenimento(13, 'entretenimento.png'),
  Esportes(14, 'esportes.png'),
  Estacionamento(59, 'transporte.png'),
  Eventos(15, 'eventos.png'),
  Exames(87, 'saude.png'),
  Farmacia(43, 'saude.png'),
  Feira(88, 'alimentacao.png'),
  Ferramentas(89, 'manutencao.png'),
  Festas(16, 'festas.png'),
  Filhos(17, 'filhos.png'),
  Financiamento(90, 'money.png'),
  Fotografia(91, 'hobbies.png'),
  Franquias(92, 'investimentos.png'),
  Freelance(60, 'money.png'),
  GiftCards(61, 'presentes.png'),
  Higiene(62, 'cuidados_pessoais.png'),
  Hobbies(18, 'hobbies.png'),
  Hotel(44, 'viagem.png'),
  Impostos(19, 'impostos.png'),
  Imprevistos(20, 'imprevistos.png'),
  Internet(45, 'tecnologia.png'),
  Investimentos(21, 'investimentos.png'),
  Jogos(22, 'jogos.png'),
  Juros(93, 'money.png'),
  Lavanderia(63, 'roupas.png'),
  Lazer(23, 'lazer.png'),
  Licencas(64, 'tecnologia.png'),
  Limpeza(94, 'manutencao.png'),
  Livros(24, 'livros.png'),
  Manutencao(25, 'manutencao.png'),
  Marketing(95, 'tecnologia.png'),
  MaterialEscolar(65, 'livros.png'),
  Mensalidade(66, 'educacao.png'),
  Mobiliario(96, 'compras.png'),
  Moradia(46, 'aluguel.png'),
  Musica(26, 'musica.png'),
  Outros(99, 'outros.png'),
  Padaria(47, 'alimentacao.png'),
  Papelaria(48, 'livros.png'),
  Parcelas(67, 'contas.png'),
  Presentes(27, 'presentes.png'),
  PrevidenciaPrivada(97, 'seguros.png'),
  Reembolso(98, 'money.png'),
  RefeicoesTrabalho(68, 'alimentacao.png'),
  Reparos(69, 'manutencao.png'),
  Restaurante(49, 'alimentacao.png'),
  Roupas(28, 'roupas.png'),
  Salario(50, 'money.png'),
  Saude(29, 'saude.png'),
  Seguros(30, 'seguros.png'),
  Servicos(51, 'contas.png'),
  Streaming(70, 'entretenimento.png'),
  Supermercado(52, 'alimentacao.png'),
  Taxas(54, 'impostos.png'),
  Tecnologia(31, 'tecnologia.png'),
  Telefone(53, 'tecnologia.png'),
  Transporte(32, 'transporte.png'),
  VendaDeItens(100, 'money.png'),
  Viagem(33, 'viagem.png')
  ;

  const CategoriaEnum(this.id, this.icone);
  final int id;
  final String icone;
  String get nome => Strings.CATEGORIA_NOMES[id] ?? '';

  static final Map<int, CategoriaEnum> _findById = Map.fromEntries(
    CategoriaEnum.values.map((value) => MapEntry(value.id, value)),
  );

  static CategoriaEnum? getById(int value) => _findById[value];
}
